#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
 #1: 1
 #3: 1,3
 #6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?

require "prime"

class Integer
  def amount_of_divisors
    divisors = 0
    n = 1
    while n <= self ** 0.5
      if self.modulo(n) == 0
        divisors += 1
        divisors += 1 unless self / n == n
      end
      n += 1
    end
    return divisors
  end
end

first = nil
t_number = 0
next_value = 1

while first == nil
  t_number += next_value
  next_value += 1
  first = t_number if t_number.amount_of_divisors > 500
end

p first
